### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by kkeeth** [k-kuwahara/pick-lunch-menu#2]
List of functions to be added

* [ ] retain previous menu acquired
* show `ぐるなび` page from menu display modal
  * [x]  register `ぐるなび` account,  get access key
  * [ ] implement

**Comment by yumemi-kuwahara** [comment]
* [x] add `searchbar` into segment page
https://ionicframework.com/docs/components/#searchbar
* [ ] add icons into segment page's list
  * in edit page, enable to register icon image
* [ ] add `config` page
* [ ] add image upload or select function into `edit` page
